image: node:20

stages:
  - test
  - publish

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - npm install
    - node test.js
  only:
    - main
    - merge_requests

publish:
  stage: publish
  script:
    - npm install
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
    - npm publish --access public
  only:
    - tags
  except:
    - branches
